### ISSUE TITLE
Icon requests

### ISSUE THREAD

**Issue by pizzadude** [cbrnix/Flatery#12]
Hi, can you please add the icons for these applications? Thanks for making this theme btw, it's really nice.

Strawberry music player ( strawberry)
https://www.strawberrymusicplayer.org/

Discord ( com.discordapp.Discord = flatpak version )

Cawbird ( uk.co.ibboard.cawbird )
https://github.com/IBBoard/cawbird
Original icon for cawbird: https://repository-images.githubusercontent.com/200412125/d0b61180-e21e-11e9-9a3b-a15bdc0c45c4

**Comment by cbrnix** [comment]
Added

**Comment by cbrnix** [comment]
strawberry added

**Comment by pizzadude** [comment]
Thanks! :)
