### ISSUE TITLE
Some Steam Games and Minecraft

### ISSUE THREAD

**Issue by creepertron95** [cbrnix/Flatery#13]
- [x] AdVenture Capitalist
Icon Name: `steam_icon_346900`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/346900/1d08a726668576b4477749f0a9bda1101c3a0883.ico)

- [x] Brawlhalla
Icon Name: `steam_icon_291550`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/291550/fd85dd54100066873d8a3f910e540ccaa7053ddd.ico)

- [x] Game Dev Tycoon
Icon Name: `steam_icon_239820`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/239820/7e218b4c77b725da973c89b89158807784532aaa.ico)

- [x] Garry's Mod
Icon Name: `steam_icon_4000`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/4000/01b545c997d68f6c4ac18ccef6c57d1d5d690e03.ico)

- [x] Minecraft
Icon Name: `minecraft`
[Icon Link](https://camo.githubusercontent.com/5975acfac213a443fa42bb60ca943de2338b42a6/687474703a2f2f696d616765732e77696b69612e636f6d2f796f67626f782f696d616765732f642f64642f4d696e6563726166745f426c6f636b2e737667)

- [x] Minetest
Icon Name: `minetest`
[Icon Link](https://thumbnails.pcgamingwiki.com/7/73/Minetest-logo.svg/300px-Minetest-logo.svg.png)

- [x] Portal
Icon Name: `steam_icon_400`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/400/c7cb09b9f0fbb9589b4bd5a8217c8333c4d8204e.ico)

- [x] Portal 2
Icon Name: `steam_icon_620`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/620/25a5a16b2423bf7487ac5340b5b0948cef48c5f8.ico)

- [x] Robocraft
Icon Name: `steam_icon_301520`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/301520/0154a4ca9d1d9e474af35255ed7685b685b58f8b.ico)

- [x] RPG Maker MV
Icon Name: `steam_icon_363890`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/363890/c8ba6022f5fd4dc06668d277c5d2bbbcb56dd6d2.ico)

- [x] Team Fortress 2
Icon Name: `steam_icon_440`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/440/033bdd91842b6aca0633ee1e5f3e6b82f2e8962f.ico)

- [x] Toribash
Icon Name: `steam_icon_248570`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/248570/7642e8aaf8d97a5fca68d749ed5cdd548cbb6d35.jpg)

- [x] Unturned
Icon Name: `steam_icon_304930`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/304930/7500f9e8568184afab30645d9fb0d18cdb4100fb.ico)

- [x] Stick Fight: The Game
Icon Name: `steam_icon_674940`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/674940/3bc3da38bc5096be8ee805a23e60516075158b5f.ico)

- [x] Skullgirls
Icon Name: `steam_icon_245170`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/245170/a7aade931f7207989b1886a53a07002054135425.ico)

- [x] Portal Stories: Mel
Icon Name: `steam_icon_317400`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/317400/9c6862818fd7cf4ee47aa90255f723ef31269000.ico)

- [x] Moe Era
Icon Name: `steam_icon_1159660`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/1159660/fa93259df4383278a4b079f1f1bcb5ab78ff14b2.ico)

- [x] Helltaker
Icon Name: `steam_icon_1289310`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/1289310/422a9fca5c48af82a10295710f581caaf973184e.ico)

- [x] BeamNG.drive
Icon Name: `steam_icon_284160`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/284160/72037f753bb4f49cd9e7d5c18bc6431551177597.ico)

- [x] Hypnospace Outlaw
Icon Name: `steam_icon_844590`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/844590/70746ecffd9189c4626162eaf950ae110a081c4b.ico)

- [x] Muse Dash
Icon Name: `steam_icon_774171`
[Icon Link](https://lh3.googleusercontent.com/g_fCBh_ccmnRUswmiXDknHzp6LJnkjfFztmQpl2tzfeFWhfrSBK6F1iyhPgF94pPcQM=s180)

- [x] Clustertruck
Icon Name: `steam_icon_397950`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/397950/8fe1c44361e24d405c3c82bfbbafd661db8b7e78.ico)

- [x] Baldi's Basics Plus
Icon Name: `steam_icon_1275890`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/1275890/d67f1831fd9b60a30e1cb0ba3893c28c6f9e66c1.ico)

- [x] Distance
Icon Name: `steam_icon_233610`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/233610/2c80f9be3bb1d8278ffd7d37ecfd451f1b105078.ico)

- [x] Octodad - Dadliest Catch
Icon Name: `steam_icon_224480`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/224480/b2d5f93141aeb8a2b96b7bf3b5887a125debc720.ico)

- [x] Cuphead
Icon Name: `steam_icon_268910`
[Icon Link](https://user-images.githubusercontent.com/53346722/66120658-fa659480-e5a0-11e9-9c6a-247a1605159e.jpg)

- [x] Undertale
Icon Name: `steam_icon_391540`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/391540/60e1002598c4aacebe1e0818964117d1d8da13af.ico)

- [x] World of Goo
Icon Name: `steam_icon_22000`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/22000/836cb57925c99e3d8af75443f892e5a452f72649.ico)

- [x] Move or Die
Icon Name: `steam_icon_323850`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/323850/53cc8427ae570dd64b8f1a25bf7b1ea432019853.ico)

- [x] Besiege
Icon Name: `steam_icon_346010`
[Icon Link](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/346010/f567cfb6308472b4ed09d7c75b58596a9bbdc8e3.ico)

**Comment by creepertron95** [comment]
Here is the actual full icon for Distance.

![distancefullicon](https://user-images.githubusercontent.com/53346722/95768187-8cf04780-0c7b-11eb-926a-02c9e246092d.png)

**Comment by cbrnix** [comment]
Okay. As time appears, I will. I think by the weekend

**Comment by creepertron95** [comment]
@cbrnix I created an icon for the game, Among Us. The steam icon name is `steam_icon_945360`.

![Among_Us](https://user-images.githubusercontent.com/53346722/96145991-688aaa00-0ecb-11eb-9b8f-b49bbf2f9b01.png)
[Among_Us.zip](https://github.com/cbrnix/Flatery/files/5385633/Among_Us.zip)

**Comment by cbrnix** [comment]
make the highlight oval and everything is fine :)

**Comment by creepertron95** [comment]
@cbrnix Modified Among Us Icon:

![Among_Us](https://user-images.githubusercontent.com/53346722/96148694-1eef8e80-0ece-11eb-807c-3bbad2066364.png)
[Among_Us.zip](https://github.com/cbrnix/Flatery/files/5385821/Among_Us.zip)

**Comment by creepertron95** [comment]
@cbrnix Probably would be a good idea to commit those to a tools folder in the repo for future contributors.

**Comment by creepertron95** [comment]
Thank You.
