### ISSUE TITLE
Contribution Guidelines?

### ISSUE THREAD

**Issue by creepertron95** [cbrnix/Flatery#14]
Hello, I was wondering if there are any contribution guidelines for creating an icon or how an icon should be. What is the usual creation process of the icons? I wanted to try at creating some.

**Comment by cbrnix** [comment]
I myself work intuitively. Therefore, even about some standards I can not say anything. There are forms (I can throw them off), there are blanks. There is a palette (material design) - in it the main tone is 400. Everything that is lighter is closer to the viewer, what is darker is further away.

**Comment by cbrnix** [comment]
Made it a separate repository. While in this form
https://github.com/cbrnix/Flatery-DIY
