### ISSUE TITLE
Discord tray icon doesn't get used.

### ISSUE THREAD

**Issue by baduhai** [cbrnix/Flatery#15]
As the title says, while there are discord tray icons, for some reason they don't get used. I'm on Plasma 5.21. This could also be an upstream bug, who knows.

**Comment by cbrnix** [comment]
Yes, I noticed this problem.  Moreover, it is using the wrong size.  Most likely because discord refers to its own icon and does not pick up others.  As far as I know, other icon themes have this problem.  Let's see if it will somehow be resolved

**Comment by spamegg1** [comment]
Discord has a hard-coded tray icon. It can only be replaced by using Hardcode-Tray:
https://github.com/bilelmoussaoui/Hardcode-Tray
