### ISSUE TITLE
Missing desktop application icons

### ISSUE THREAD

**Issue by se7enge** [cbrnix/Flatery#18]
Hey man great work on this icon pack. Not sure if this is the appropriate place to ask, but I was wondering if there is any chance of some of applications, that are missing dedicated icons, to get updated with said dedicated icons? Obviously you can't make an icon for every application out there, but I do believe there are some more common ones which are currently lacking icons: and thus show the default icon instead. The two most prominent ones on my system are 'signal-desktop' and 'qBitorrent'.

Again, thanks for your work on this project, any advice is much appreciated :)

**Comment by cbrnix** [comment]
I added the qbittorrent icon (apparently, the name changed). Later I will add a link and make signal-desktop

**Comment by cbrnix** [comment]
Added
