### ISSUE TITLE
[Icon Request] HakuNeko Desktop

### ISSUE THREAD

**Issue by creepertron95** [cbrnix/Flatery#2]
Hi, I would like to request an icon for HakuNeko in the Flatery icon theme.

- Name - HakuNeko Desktop
- Icon Name - `hakuneko-desktop`
- Website - https://github.com/manga-download/hakuneko
- Original Icon - 
![hakuneko-desktop](https://user-images.githubusercontent.com/53346722/76154157-4e6b2c80-609d-11ea-9306-9663edd910b0.png)

**Comment by cbrnix** [comment]
Added

**Comment by creepertron95** [comment]
Thank You
