### ISSUE TITLE
No postman icon

### ISSUE THREAD

**Issue by dipto0321** [cbrnix/Flatery#21]
How can I add a icon?

**Comment by cbrnix** [comment]
They already exist:
com.getpostman.Postman.svg
postman.svg

**Comment by dipto0321** [comment]
Hi @cbrnix ,
Thanks for your response. Then why it's not showing. I'm using Manjaro linux. Any idea?

**Comment by cbrnix** [comment]
Most likely, the desktop file contains a direct link to the icon.
Search for .desktop and in the line
icon = ...
write "postman"
