### ISSUE TITLE
Suggestions for missing icons?

### ISSUE THREAD

**Issue by guitaristtom** [cbrnix/Flatery#22]
Discord PTB, Sublime Merge, and Plex Media Player are all missing icons in the pack.

I noticed that Discord and Discord Canary have icons, but PTB did not.

Sublime Text also has an icon, but not the new Sublime Merge.

**Comment by cbrnix** [comment]
I added missing links

**Comment by dalamanster** [comment]
Also If I may add few ideas:
- virtualbox
- keepass / keepasxc
- securecrt

thanks for your work
