### ISSUE TITLE
Request Icons 

### ISSUE THREAD

**Issue by EliaHKM** [cbrnix/Flatery#27]
Hi,
Could you please add icons for these apps

- equate  [https://git.enlightenment.org/apps/equate.git](url)
- Oomox [https://flathub.org/apps/details/com.github.themix_project.Oomox](url)
- Persepolis [ https://persepolisdm.github.io/](url)
- Rage [https://download.enlightenment.org/rel/apps/rage/rage-0.3.1.tar.xz](url)
- Ecrire [ https://github.com/Obsidian-StudiosInc/ecrire](url)
- ephoto [https://download.enlightenment.org/rel/apps/ephoto/ephoto-1.5.tar.xz](url)
- Bzoing [https://snapcraft.io/search?q=bzoing](url)
- Econnman [https://download.enlightenment.org/rel/apps/econnman/econnman-1.1.tar.xz](url)
- Terminology [https://download.enlightenment.org/rel/apps/terminology/terminology-1.11.0.tar.xz](url)
- Elementary  (It's part of enlightenment)

Thanks man I love Your work
peace ✌

**Comment by cbrnix** [comment]
As soon as the time appears, I will add :) Did you send it? Optional, but thanks

**Comment by cbrnix** [comment]
Did it. However, I'm not sure about the "elementary", since I don't know the exact name of the icon.
In addition, you most likely have to edit the line in bzoing.desktop, because there is a direct link to the icon file 
Icon=${SNAP}/meta/gui/icon.png
to
Icon=bzoing

**Comment by EliaHKM** [comment]
> As soon as the time appears, I will add :) Did you send it? Optional, but thanks

Send what?

**Comment by EliaHKM** [comment]
Here is elementary and Econnman from Plataro icons [https://imgur.com/beuSSUk](url)

thanks man

**Comment by cbrnix** [comment]
> Here is elementary and Econnman from Plataro icons [https://imgur.com/beuSSUk](url)
> 
> thanks man

Ok. I made them look like

**Comment by EliaHKM** [comment]
thanks man
