### ISSUE TITLE
[Icon Requests] Some Games

### ISSUE THREAD

**Issue by creepertron95** [cbrnix/Flatery#3]
- [x] Aseprite
Icon Names - `aseprite` `steam_icon_431730`
[Icon Link](https://github.com/aseprite/aseprite/blob/master/data/icons/ase64.png)

- [x] Cave Story NX
Icon Name - `com.gitlab.coringao.cavestory-nx`
[Icon Link](https://dl.flathub.org/repo/appstream/x86_64/icons/128x128/com.gitlab.coringao.cavestory-nx.png)

- [x] Doki Doki Literature Club
Icon Names - `doki-doki-literature-club` `steam_icon_698780`
[Icon Link](https://e.snmc.io/lk/o/x/8aede459a471ebfbac6ec7a122f3c7d6/6683185)

- [x] Extreme Tux Racer
Icon Name - `etr`
[Icon Link](https://dl.flathub.org/repo/appstream/x86_64/icons/128x128/net.sourceforge.ExtremeTuxRacer.png)

- [x] LBreakout2
Icon Name - `lbreakout2`
[Icon Link](https://d2.alternativeto.net/dist/icons/lbreakout2_99888.png?width=64&height=64&mode=crop&upscale=false)

- [x] Mahjongg
Icon Name `gnome-mahjongg`
[Icon Link](https://dl.flathub.org/repo/appstream/x86_64/icons/128x128/org.gnome.Mahjongg.png)

- [x] Peg-E
Icon Name `peg-e`
[Icon Link](https://dl.flathub.org/repo/appstream/x86_64/icons/128x128/org.gottcode.Peg-E.png)

- [x] Ren'Py
Icon Name `renpy`
[Icon Link](https://user-images.githubusercontent.com/35447794/60633389-d7c8b180-9de0-11e9-95b3-7d5e3c18f68a.png)

- [x] Ren'Py Demo
Icon Name `renpy-demo`
[Icon Link](https://user-images.githubusercontent.com/53346722/70195775-41b8f000-16cc-11ea-9200-24e14879fa87.png)

- [x] The Question
Icon Name `renpy-thequestion`
[Icon Link](https://user-images.githubusercontent.com/53346722/70195859-86dd2200-16cc-11ea-9dc4-0d4f63fd9691.png)

**Comment by cbrnix** [comment]
Added
