### ISSUE TITLE
Missing and request icons

### ISSUE THREAD

**Issue by EliaHKM** [cbrnix/Flatery#30]
Hi 🙋🏻,
Missing icon
1. Ubuntu software
2. startup applications
3. startup disk creator

Request icons

- flatseal 
- RPCS3 flatpack and snap
- Basemark GPU
- fontvuer https://snapcraft.io/fontvuer 
- emote https://snapcraft.io/emote 
- flatseal https://flathub.org/apps/details/com.github.tchx84.Flatseal 
- xemu https://xemu.app 
- tenacity https://github.com/tenacityteam/tenacity 
- reactions https://flathub.org/apps/details/dev.atoft.Reactions 
- youtubedl-gui https://flathub.org/apps/details/io.github.JaGoLi.ytdl_gui 
- YOGA https://flathub.org/apps/details/org.flozz.yoga-image-optimizer 

You're missing red folders

thanks 😊

**Comment by cbrnix** [comment]
Basemark GPU was already there. Perhaps it just has a direct link to the icon file.
I added: 
appimagekit-rpcs3 basemarkgpu com.github.tchx84.Flatseal com.github.treagod.spectator dev.atoft.Reactions emote fontvuer rpcs3 tenacity ubuntu-kylin-software-center ubuntusoftware usb-creator-gtk usb-creator-kde xemu yoga youtubedl-gui
