### ISSUE TITLE
[Icon Request] Simplenote

### ISSUE THREAD

**Issue by SaeedBaig** [cbrnix/Flatery#5]
Hi if you don't mind I'd like to request an icon for 1 app:
Name: [Simplenote](https://simplenote.com/)
icon-name: `simplenote`
Original icon:
![Logo_of_Simplenote](https://user-images.githubusercontent.com/29703429/80562884-75563700-8a2c-11ea-8025-012d2b9567e5.png)

**Comment by cbrnix** [comment]
Added
