### ISSUE TITLE
[Icon Requests] MX Linux Tools

### ISSUE THREAD

**Issue by creepertron95** [cbrnix/Flatery#6]
- [x] MX Tools
Icon Name: `mx-tools`
![mx-tools](https://user-images.githubusercontent.com/53346722/81211850-9ae9c000-8f99-11ea-840c-f5a43a64f62c.png)

- [x] MX Snapshot
Icon Name: `mx-snapshot`
![mx-snapshot](https://user-images.githubusercontent.com/53346722/81211920-b3f27100-8f99-11ea-9107-27a32ab1fbeb.png)

- [x] MX Welcome
Icon Name: `mx-welcome`
![mx-welcome](https://user-images.githubusercontent.com/53346722/81211989-cf5d7c00-8f99-11ea-9aa3-4a054e8213d0.png)

- [x] MX Network Assistant
Icon Name: `mx-network-assistant`
![mx-network-assistant](https://user-images.githubusercontent.com/53346722/81212178-1e0b1600-8f9a-11ea-9b47-d54935aad990.png)

- [x] iDeviceMounter
Icon Name: `idevice`
![idevice](https://user-images.githubusercontent.com/53346722/81212233-34b16d00-8f9a-11ea-9775-9305dcff75e0.png)

- [x] MX Boot Options
Icon Name: `mx-boot-options`
![mx-boot-options](https://user-images.githubusercontent.com/53346722/81212293-4b57c400-8f9a-11ea-9ba2-d1c4f40a3ab1.png)

- [x] MX Boot Repair
Icon Name: `mx-boot-repair`
![mx-bootrepair](https://user-images.githubusercontent.com/53346722/81212378-73472780-8f9a-11ea-963e-cd11b490a249.png)

- [x] MX Cleanup
Icon Name: `mx-cleanup`
![mx-cleanup](https://user-images.githubusercontent.com/53346722/81212460-8a861500-8f9a-11ea-9a3b-bcc0da344234.png)

- [x] MX Codecs
Icon Name: `mx-codecs`
![mx-codecs](https://user-images.githubusercontent.com/53346722/81212819-0e400180-8f9b-11ea-832b-ae896e4b5774.png)

- [x] MX Conky
Icon Name: `mx-conky`
![mx-conky](https://user-images.githubusercontent.com/53346722/81212844-1c8e1d80-8f9b-11ea-85c5-89830a08b336.png)

- [x] MX DateTime
Icon Name: `mx-datetime`
![mx-datetime](https://user-images.githubusercontent.com/53346722/81212918-3def0980-8f9b-11ea-86b5-6ec39ec883e6.png)

- [x] MX Fix GPG Keys
Icon Name: `GPG-Key4`
![GPG-Key4](https://user-images.githubusercontent.com/53346722/81212959-4e9f7f80-8f9b-11ea-9885-551fe05146af.png)

- [x] MX Live USB Maker
Icon Name: `mx-live-usb-maker`
![mx-live-usb-maker](https://user-images.githubusercontent.com/53346722/81213007-5e1ec880-8f9b-11ea-88f4-832af1ddd370.png)

- [x] MX Menu Editor
Icon Name: `mx-menu-editor`
![mx-menu-editor](https://user-images.githubusercontent.com/53346722/81213047-6b3bb780-8f9b-11ea-81a7-d3176f215626.png)

- [x] MX Package Installer
Icon Name: `mx-package-installer`
![mx-packageinstaller](https://user-images.githubusercontent.com/53346722/81213146-96260b80-8f9b-11ea-8d6c-813f7355882c.png)

- [x] MX Repo Manager
Icon Name: `mx-repo-manager`
![mx-repo-manager](https://user-images.githubusercontent.com/53346722/81213170-a0e0a080-8f9b-11ea-90b7-675c282acf18.png)

- [x] MX Select Sound
Icon Name: `mx-select-sound`
![mx-select-sound](https://user-images.githubusercontent.com/53346722/81213212-ab9b3580-8f9b-11ea-906b-3ba3ce9d6a87.png)

- [x] MX Timeset GUI
Icon Name: `mx-timeset-gui-icon`
![preferences-system-time svg](https://user-images.githubusercontent.com/53346722/81213282-c40b5000-8f9b-11ea-89ae-7ec75622dfcb.png)

- [x] MX Tweak
Icon Name: `mx-tweak`
![mx-tweak](https://user-images.githubusercontent.com/53346722/81213312-ccfc2180-8f9b-11ea-93ef-51e6c3d0958f.png)

- [x] MX User
Icon Name: `mx-user`
![mx-user](https://user-images.githubusercontent.com/53346722/81213335-d4bbc600-8f9b-11ea-946b-38e3d8bb0693.png)

- [x] Quick System Info
Icon Name: `mx-qsi`
![mx-qsi](https://user-images.githubusercontent.com/53346722/81213386-e3a27880-8f9b-11ea-86dc-e501141dcd6b.png)

- [x] System Keyboard MX
Icon Name: `system-keyboard-mx`
![system-keyboard-mx svg](https://user-images.githubusercontent.com/53346722/81213474-046ace00-8f9c-11ea-876e-e5d459f4957b.png)

- [x] MX Distributor Logo
Icon Name: `distributor-logo-mx`
![MXStart](https://user-images.githubusercontent.com/53346722/81213599-3a0fb700-8f9c-11ea-8cce-2c67539245f3.png)

**Comment by creepertron95** [comment]
Oops, I need to edit this issue real quick.

**Comment by cbrnix** [comment]
Already doing it. I'll pour it in a couple of days

**Comment by creepertron95** [comment]
Thank you, @cbrnix.

**Comment by cbrnix** [comment]
Part I added. If it’s not difficult for you, check (there is a list in the commit). When I have a weekend, I will finish the rest

**Comment by cbrnix** [comment]
Done
