### ISSUE TITLE
[Icon Request] SRB2 Games

### ISSUE THREAD

**Issue by creepertron95** [cbrnix/Flatery#7]
- [x] Sonic Robo Blast 2
Icon Name: `org.srb2.SRB2`
![](https://flathub.org/repo/appstream/x86_64/icons/128x128/org.srb2.SRB2.png)

- [x] Sonic Robo Blast 2 Kart
Icon Name: `org.srb2.SRB2Kart`
![](https://flathub.org/repo/appstream/x86_64/icons/128x128/org.srb2.SRB2Kart.png)

**Comment by cbrnix** [comment]
Done
